FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
        build-essential \
        cmake \
        wget \
        curl \
        ca-certificates \
        sudo \
        git \
        bzip2 \
        libx11-6 \
        python-qt4 \
        libjpeg-dev \
        sudo \
        libpng-dev \
        libeigen3-dev \
        libgoogle-glog-dev \
        libsuitesparse-dev \
        libsparsehash-dev \
        libboost-all-dev \
        libatlas-base-dev &&\
    rm -rf /var/lib/apt/lists/*

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Install Miniconda and Python 3.6
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV PATH=/home/user/miniconda/bin:$PATH
RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda install -y python==3.6.9 \
 && conda clean -ya

# CUDA 10.2-specific steps
RUN conda install -y -c pytorch \
    cudatoolkit=10.1 \
    "pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0" \
    "torchvision=0.5.0=py36_cu101" \
 && conda clean -ya

RUN cd /home/user \
    && git clone https://github.com/yanx27/JS3C-Net.git \
    && conda install libboost \
    # && pip install spconv-cu102 \
    ## && conda install -c daleydeng gcc-5 \
    && conda install Cython

RUN cd /home/user/JS3C-Net/lib/ \
    && sh compile.sh

#ENV root=/home/user/JS3C-Net

WORKDIR /home/user

